# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriel/projects/Xonix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriel/projects/Xonix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/projects/Xonix/CMakeFiles /home/gabriel/projects/Xonix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/projects/Xonix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Xonix

# Build rule for target.
Xonix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Xonix
.PHONY : Xonix

# fast build rule for target.
Xonix/fast:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/build
.PHONY : Xonix/fast

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/main.s
.PHONY : main.s

# target to build an object file
src/enemigo.o:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/enemigo.o
.PHONY : src/enemigo.o

# target to preprocess a source file
src/enemigo.i:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/enemigo.i
.PHONY : src/enemigo.i

# target to generate assembly for a file
src/enemigo.s:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/enemigo.s
.PHONY : src/enemigo.s

# target to build an object file
src/personaje.o:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/personaje.o
.PHONY : src/personaje.o

# target to preprocess a source file
src/personaje.i:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/personaje.i
.PHONY : src/personaje.i

# target to generate assembly for a file
src/personaje.s:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/personaje.s
.PHONY : src/personaje.s

# target to build an object file
src/poligono.o:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/poligono.o
.PHONY : src/poligono.o

# target to preprocess a source file
src/poligono.i:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/poligono.i
.PHONY : src/poligono.i

# target to generate assembly for a file
src/poligono.s:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/poligono.s
.PHONY : src/poligono.s

# target to build an object file
src/timer.o:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/timer.o
.PHONY : src/timer.o

# target to preprocess a source file
src/timer.i:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/timer.i
.PHONY : src/timer.i

# target to generate assembly for a file
src/timer.s:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/timer.s
.PHONY : src/timer.s

# target to build an object file
src/xonix.o:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/xonix.o
.PHONY : src/xonix.o

# target to preprocess a source file
src/xonix.i:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/xonix.i
.PHONY : src/xonix.i

# target to generate assembly for a file
src/xonix.s:
	$(MAKE) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/xonix.s
.PHONY : src/xonix.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Xonix"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/enemigo.o"
	@echo "... src/enemigo.i"
	@echo "... src/enemigo.s"
	@echo "... src/personaje.o"
	@echo "... src/personaje.i"
	@echo "... src/personaje.s"
	@echo "... src/poligono.o"
	@echo "... src/poligono.i"
	@echo "... src/poligono.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/xonix.o"
	@echo "... src/xonix.i"
	@echo "... src/xonix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

