# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabo/projects/Xonix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabo/projects/Xonix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabo/projects/Xonix/CMakeFiles /home/gabo/projects/Xonix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabo/projects/Xonix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Xonix

# Build rule for target.
Xonix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Xonix
.PHONY : Xonix

# fast build rule for target.
Xonix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/build
.PHONY : Xonix/fast

src/enemigo.o: src/enemigo.cpp.o
.PHONY : src/enemigo.o

# target to build an object file
src/enemigo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/enemigo.cpp.o
.PHONY : src/enemigo.cpp.o

src/enemigo.i: src/enemigo.cpp.i
.PHONY : src/enemigo.i

# target to preprocess a source file
src/enemigo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/enemigo.cpp.i
.PHONY : src/enemigo.cpp.i

src/enemigo.s: src/enemigo.cpp.s
.PHONY : src/enemigo.s

# target to generate assembly for a file
src/enemigo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/enemigo.cpp.s
.PHONY : src/enemigo.cpp.s

src/personaje.o: src/personaje.cpp.o
.PHONY : src/personaje.o

# target to build an object file
src/personaje.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/personaje.cpp.o
.PHONY : src/personaje.cpp.o

src/personaje.i: src/personaje.cpp.i
.PHONY : src/personaje.i

# target to preprocess a source file
src/personaje.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/personaje.cpp.i
.PHONY : src/personaje.cpp.i

src/personaje.s: src/personaje.cpp.s
.PHONY : src/personaje.s

# target to generate assembly for a file
src/personaje.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/personaje.cpp.s
.PHONY : src/personaje.cpp.s

src/poligono.o: src/poligono.cpp.o
.PHONY : src/poligono.o

# target to build an object file
src/poligono.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/poligono.cpp.o
.PHONY : src/poligono.cpp.o

src/poligono.i: src/poligono.cpp.i
.PHONY : src/poligono.i

# target to preprocess a source file
src/poligono.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/poligono.cpp.i
.PHONY : src/poligono.cpp.i

src/poligono.s: src/poligono.cpp.s
.PHONY : src/poligono.s

# target to generate assembly for a file
src/poligono.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/poligono.cpp.s
.PHONY : src/poligono.cpp.s

src/timer.o: src/timer.cpp.o
.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/xonix.o: src/xonix.cpp.o
.PHONY : src/xonix.o

# target to build an object file
src/xonix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/xonix.cpp.o
.PHONY : src/xonix.cpp.o

src/xonix.i: src/xonix.cpp.i
.PHONY : src/xonix.i

# target to preprocess a source file
src/xonix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/xonix.cpp.i
.PHONY : src/xonix.cpp.i

src/xonix.s: src/xonix.cpp.s
.PHONY : src/xonix.s

# target to generate assembly for a file
src/xonix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Xonix.dir/build.make CMakeFiles/Xonix.dir/src/xonix.cpp.s
.PHONY : src/xonix.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Xonix"
	@echo "... src/enemigo.o"
	@echo "... src/enemigo.i"
	@echo "... src/enemigo.s"
	@echo "... src/personaje.o"
	@echo "... src/personaje.i"
	@echo "... src/personaje.s"
	@echo "... src/poligono.o"
	@echo "... src/poligono.i"
	@echo "... src/poligono.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/xonix.o"
	@echo "... src/xonix.i"
	@echo "... src/xonix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

